// Chemical Data - Comprehensive database of chemicals for the chemistry lab simulation

export interface Chemical {
  id: string;
  name: string;
  formula: string;
  type: "metal" | "nonmetal" | "molecule" | "salt" | "acid" | "base" | "oxide";
  state: "solid" | "liquid" | "gas" | "aqueous";
  cation?: string;
  anion?: string;
  color?: string;
  description?: string;
}

// Comprehensive chemical database - 152 chemicals
export const CHEMICALS: Chemical[] = [
  // Metals
  {
    id: "1",
    name: "Sodium",
    formula: "Na",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "2",
    name: "Magnesium",
    formula: "Mg",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "3",
    name: "Zinc",
    formula: "Zn",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "4",
    name: "Iron",
    formula: "Fe",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "5",
    name: "Copper",
    formula: "Cu",
    type: "metal",
    state: "solid",
    color: "#FF8C00",
  },
  {
    id: "6",
    name: "Silver",
    formula: "Ag",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "7",
    name: "Gold",
    formula: "Au",
    type: "metal",
    state: "solid",
    color: "#FFD700",
  },
  {
    id: "8",
    name: "Aluminum",
    formula: "Al",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "9",
    name: "Calcium",
    formula: "Ca",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "10",
    name: "Potassium",
    formula: "K",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "41",
    name: "Aluminum",
    formula: "Al",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "42",
    name: "Lead",
    formula: "Pb",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "43",
    name: "Mercury",
    formula: "Hg",
    type: "metal",
    state: "liquid",
    color: "#C0C0C0",
  },
  {
    id: "44",
    name: "Nickel",
    formula: "Ni",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "45",
    name: "Tin",
    formula: "Sn",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "46",
    name: "Chromium",
    formula: "Cr",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "47",
    name: "Manganese",
    formula: "Mn",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "48",
    name: "Cobalt",
    formula: "Co",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "49",
    name: "Cadmium",
    formula: "Cd",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },
  {
    id: "50",
    name: "Bismuth",
    formula: "Bi",
    type: "metal",
    state: "solid",
    color: "#C0C0C0",
  },

  // Nonmetals
  {
    id: "11",
    name: "Chlorine",
    formula: "Cl2",
    type: "nonmetal",
    state: "gas",
    color: "#FFFF00",
  },
  {
    id: "12",
    name: "Oxygen",
    formula: "O2",
    type: "nonmetal",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "13",
    name: "Hydrogen",
    formula: "H2",
    type: "nonmetal",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "14",
    name: "Nitrogen",
    formula: "N2",
    type: "nonmetal",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "15",
    name: "Sulfur",
    formula: "S",
    type: "nonmetal",
    state: "solid",
    color: "#FFFF00",
  },
  {
    id: "51",
    name: "Phosphorus",
    formula: "P",
    type: "nonmetal",
    state: "solid",
    color: "#FFFF00",
  },
  {
    id: "52",
    name: "Sulfur",
    formula: "S",
    type: "nonmetal",
    state: "solid",
    color: "#FFFF00",
  },
  {
    id: "53",
    name: "Iodine",
    formula: "I2",
    type: "nonmetal",
    state: "solid",
    color: "#800080",
  },
  {
    id: "54",
    name: "Bromine",
    formula: "Br2",
    type: "nonmetal",
    state: "liquid",
    color: "#8B4513",
  },
  {
    id: "55",
    name: "Carbon",
    formula: "C",
    type: "nonmetal",
    state: "solid",
    color: "#000000",
  },
  {
    id: "56",
    name: "Silicon",
    formula: "Si",
    type: "nonmetal",
    state: "solid",
    color: "#696969",
  },

  // Molecules
  {
    id: "16",
    name: "Water",
    formula: "H2O",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "17",
    name: "Carbon Dioxide",
    formula: "CO2",
    type: "molecule",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "18",
    name: "Methane",
    formula: "CH4",
    type: "molecule",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "19",
    name: "Ammonia",
    formula: "NH3",
    type: "molecule",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "20",
    name: "Hydrogen Peroxide",
    formula: "H2O2",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "91",
    name: "Ethanol",
    formula: "C2H5OH",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "92",
    name: "Acetone",
    formula: "CH3COCH3",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "93",
    name: "Benzene",
    formula: "C6H6",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "94",
    name: "Glucose",
    formula: "C6H12O6",
    type: "molecule",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "95",
    name: "Sucrose",
    formula: "C12H22O11",
    type: "molecule",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "126",
    name: "Methanol",
    formula: "CH3OH",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "127",
    name: "Ethylene Glycol",
    formula: "C2H6O2",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "128",
    name: "Glycerol",
    formula: "C3H8O3",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },
  {
    id: "129",
    name: "Formaldehyde",
    formula: "CH2O",
    type: "molecule",
    state: "gas",
    color: "#FFFFFF",
  },
  {
    id: "130",
    name: "Acetic Anhydride",
    formula: "C4H6O3",
    type: "molecule",
    state: "liquid",
    color: "#FFFFFF",
  },

  // Salts
  {
    id: "21",
    name: "Sodium Chloride",
    formula: "NaCl",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "22",
    name: "Copper Sulfate",
    formula: "CuSO4",
    type: "salt",
    state: "solid",
    cation: "Cu2+",
    anion: "SO4^2-",
    color: "#0000FF",
  },
  {
    id: "23",
    name: "Iron Chloride",
    formula: "FeCl2",
    type: "salt",
    state: "solid",
    cation: "Fe2+",
    anion: "Cl-",
    color: "#00FF00",
  },
  {
    id: "24",
    name: "Silver Nitrate",
    formula: "AgNO3",
    type: "salt",
    state: "solid",
    cation: "Ag+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "25",
    name: "Lead Nitrate",
    formula: "Pb(NO3)2",
    type: "salt",
    state: "solid",
    cation: "Pb2+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "26",
    name: "Zinc Sulfate",
    formula: "ZnSO4",
    type: "salt",
    state: "solid",
    cation: "Zn2+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "27",
    name: "Magnesium Sulfate",
    formula: "MgSO4",
    type: "salt",
    state: "solid",
    cation: "Mg2+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "28",
    name: "Calcium Chloride",
    formula: "CaCl2",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "68",
    name: "Potassium Chloride",
    formula: "KCl",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "69",
    name: "Sodium Sulfate",
    formula: "Na2SO4",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "70",
    name: "Calcium Chloride",
    formula: "CaCl2",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "71",
    name: "Magnesium Sulfate",
    formula: "MgSO4",
    type: "salt",
    state: "solid",
    cation: "Mg2+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "72",
    name: "Potassium Nitrate",
    formula: "KNO3",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "73",
    name: "Sodium Carbonate",
    formula: "Na2CO3",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "74",
    name: "Calcium Carbonate",
    formula: "CaCO3",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "75",
    name: "Barium Sulfate",
    formula: "BaSO4",
    type: "salt",
    state: "solid",
    cation: "Ba2+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "76",
    name: "Copper(II) Sulfate",
    formula: "CuSO4",
    type: "salt",
    state: "solid",
    cation: "Cu2+",
    anion: "SO4^2-",
    color: "#0000FF",
  },
  {
    id: "77",
    name: "Iron(II) Chloride",
    formula: "FeCl2",
    type: "salt",
    state: "solid",
    cation: "Fe2+",
    anion: "Cl-",
    color: "#00FF00",
  },
  {
    id: "78",
    name: "Iron(III) Chloride",
    formula: "FeCl3",
    type: "salt",
    state: "solid",
    cation: "Fe3+",
    anion: "Cl-",
    color: "#FFA500",
  },
  {
    id: "79",
    name: "Nickel(II) Sulfate",
    formula: "NiSO4",
    type: "salt",
    state: "solid",
    cation: "Ni2+",
    anion: "SO4^2-",
    color: "#00FFFF",
  },
  {
    id: "80",
    name: "Cobalt(II) Chloride",
    formula: "CoCl2",
    type: "salt",
    state: "solid",
    cation: "Co2+",
    anion: "Cl-",
    color: "#FF00FF",
  },
  {
    id: "81",
    name: "Manganese(II) Sulfate",
    formula: "MnSO4",
    type: "salt",
    state: "solid",
    cation: "Mn2+",
    anion: "SO4^2-",
    color: "#800080",
  },
  {
    id: "82",
    name: "Chromium(III) Sulfate",
    formula: "Cr2(SO4)3",
    type: "salt",
    state: "solid",
    cation: "Cr3+",
    anion: "SO4^2-",
    color: "#008000",
  },
  {
    id: "83",
    name: "Aluminum Sulfate",
    formula: "Al2(SO4)3",
    type: "salt",
    state: "solid",
    cation: "Al3+",
    anion: "SO4^2-",
    color: "#C0C0C0",
  },
  {
    id: "84",
    name: "Zinc Nitrate",
    formula: "Zn(NO3)2",
    type: "salt",
    state: "solid",
    cation: "Zn2+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "85",
    name: "Lead(II) Nitrate",
    formula: "Pb(NO3)2",
    type: "salt",
    state: "solid",
    cation: "Pb2+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "86",
    name: "Mercury(II) Chloride",
    formula: "HgCl2",
    type: "salt",
    state: "solid",
    cation: "Hg2+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "87",
    name: "Silver Sulfate",
    formula: "Ag2SO4",
    type: "salt",
    state: "solid",
    cation: "Ag+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "88",
    name: "Barium Chloride",
    formula: "BaCl2",
    type: "salt",
    state: "solid",
    cation: "Ba2+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "89",
    name: "Strontium Nitrate",
    formula: "Sr(NO3)2",
    type: "salt",
    state: "solid",
    cation: "Sr2+",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "90",
    name: "Lithium Chloride",
    formula: "LiCl",
    type: "salt",
    state: "solid",
    cation: "Li+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "96",
    name: "Sodium Bicarbonate",
    formula: "NaHCO3",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "HCO3-",
    color: "#FFFFFF",
  },
  {
    id: "97",
    name: "Ammonium Chloride",
    formula: "NH4Cl",
    type: "salt",
    state: "solid",
    cation: "NH4+",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "98",
    name: "Ammonium Sulfate",
    formula: "(NH4)2SO4",
    type: "salt",
    state: "solid",
    cation: "NH4+",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "99",
    name: "Potassium Permanganate",
    formula: "KMnO4",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "MnO4-",
    color: "#800080",
  },
  {
    id: "100",
    name: "Sodium Thiosulfate",
    formula: "Na2S2O3",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "S2O3^2-",
    color: "#FFFFFF",
  },
  {
    id: "106",
    name: "Sodium Phosphate",
    formula: "Na3PO4",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "PO4^3-",
    color: "#FFFFFF",
  },
  {
    id: "107",
    name: "Calcium Phosphate",
    formula: "Ca3(PO4)2",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "PO4^3-",
    color: "#FFFFFF",
  },
  {
    id: "108",
    name: "Magnesium Phosphate",
    formula: "Mg3(PO4)2",
    type: "salt",
    state: "solid",
    cation: "Mg2+",
    anion: "PO4^3-",
    color: "#FFFFFF",
  },
  {
    id: "117",
    name: "Sodium Acetate",
    formula: "CH3COONa",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "CH3COO-",
    color: "#FFFFFF",
  },
  {
    id: "118",
    name: "Potassium Chromate",
    formula: "K2CrO4",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "CrO4^2-",
    color: "#FFFF00",
  },
  {
    id: "119",
    name: "Potassium Dichromate",
    formula: "K2Cr2O7",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "Cr2O7^2-",
    color: "#FFA500",
  },
  {
    id: "120",
    name: "Sodium Hypochlorite",
    formula: "NaOCl",
    type: "salt",
    state: "aqueous",
    cation: "Na+",
    anion: "OCl-",
    color: "#FFFFFF",
  },
  {
    id: "121",
    name: "Calcium Hypochlorite",
    formula: "Ca(OCl)2",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "OCl-",
    color: "#FFFFFF",
  },
  {
    id: "122",
    name: "Sodium Cyanide",
    formula: "NaCN",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "CN-",
    color: "#FFFFFF",
  },
  {
    id: "123",
    name: "Potassium Cyanide",
    formula: "KCN",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "CN-",
    color: "#FFFFFF",
  },
  {
    id: "124",
    name: "Sodium Fluoride",
    formula: "NaF",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "F-",
    color: "#FFFFFF",
  },
  {
    id: "125",
    name: "Calcium Fluoride",
    formula: "CaF2",
    type: "salt",
    state: "solid",
    cation: "Ca2+",
    anion: "F-",
    color: "#FFFFFF",
  },
  {
    id: "137",
    name: "Potassium Carbonate",
    formula: "K2CO3",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "138",
    name: "Magnesium Carbonate",
    formula: "MgCO3",
    type: "salt",
    state: "solid",
    cation: "Mg2+",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "139",
    name: "Barium Carbonate",
    formula: "BaCO3",
    type: "salt",
    state: "solid",
    cation: "Ba2+",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "140",
    name: "Sodium Bicarbonate",
    formula: "NaHCO3",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "HCO3-",
    color: "#FFFFFF",
  },
  {
    id: "141",
    name: "Potassium Bicarbonate",
    formula: "KHCO3",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "HCO3-",
    color: "#FFFFFF",
  },
  {
    id: "148",
    name: "Sodium Thiosulfate",
    formula: "Na2S2O3",
    type: "salt",
    state: "solid",
    cation: "Na+",
    anion: "S2O3^2-",
    color: "#FFFFFF",
  },
  {
    id: "149",
    name: "Potassium Thiocyanate",
    formula: "KSCN",
    type: "salt",
    state: "solid",
    cation: "K+",
    anion: "SCN-",
    color: "#FFFFFF",
  },
  {
    id: "150",
    name: "Silver Thiocyanate",
    formula: "AgSCN",
    type: "salt",
    state: "solid",
    cation: "Ag+",
    anion: "SCN-",
    color: "#FFFFFF",
  },
  {
    id: "151",
    name: "Lead(II) Thiocyanate",
    formula: "Pb(SCN)2",
    type: "salt",
    state: "solid",
    cation: "Pb2+",
    anion: "SCN-",
    color: "#FFFFFF",
  },
  {
    id: "152",
    name: "Copper(II) Thiocyanate",
    formula: "Cu(SCN)2",
    type: "salt",
    state: "solid",
    cation: "Cu2+",
    anion: "SCN-",
    color: "#000000",
  },

  // Acids
  {
    id: "29",
    name: "Hydrochloric Acid",
    formula: "HCl",
    type: "acid",
    state: "aqueous",
    anion: "Cl-",
    color: "#FFFFFF",
  },
  {
    id: "57",
    name: "Sulfuric Acid",
    formula: "H2SO4",
    type: "acid",
    state: "aqueous",
    anion: "SO4^2-",
    color: "#FFFFFF",
  },
  {
    id: "58",
    name: "Nitric Acid",
    formula: "HNO3",
    type: "acid",
    state: "aqueous",
    anion: "NO3-",
    color: "#FFFFFF",
  },
  {
    id: "59",
    name: "Phosphoric Acid",
    formula: "H3PO4",
    type: "acid",
    state: "aqueous",
    anion: "PO4^3-",
    color: "#FFFFFF",
  },
  {
    id: "60",
    name: "Hydrobromic Acid",
    formula: "HBr",
    type: "acid",
    state: "aqueous",
    anion: "Br-",
    color: "#FFFFFF",
  },
  {
    id: "61",
    name: "Hydroiodic Acid",
    formula: "HI",
    type: "acid",
    state: "aqueous",
    anion: "I-",
    color: "#FFFFFF",
  },
  {
    id: "62",
    name: "Carbonic Acid",
    formula: "H2CO3",
    type: "acid",
    state: "aqueous",
    anion: "CO3^2-",
    color: "#FFFFFF",
  },
  {
    id: "101",
    name: "Acetic Acid",
    formula: "CH3COOH",
    type: "acid",
    state: "aqueous",
    anion: "CH3COO-",
    color: "#FFFFFF",
  },
  {
    id: "102",
    name: "Formic Acid",
    formula: "HCOOH",
    type: "acid",
    state: "aqueous",
    anion: "HCOO-",
    color: "#FFFFFF",
  },
  {
    id: "103",
    name: "Oxalic Acid",
    formula: "H2C2O4",
    type: "acid",
    state: "solid",
    anion: "C2O4^2-",
    color: "#FFFFFF",
  },
  {
    id: "104",
    name: "Citric Acid",
    formula: "C6H8O7",
    type: "acid",
    state: "solid",
    anion: "C6H5O7^3-",
    color: "#FFFFFF",
  },

  // Bases
  {
    id: "33",
    name: "Sodium Hydroxide",
    formula: "NaOH",
    type: "base",
    state: "solid",
    cation: "Na+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "34",
    name: "Potassium Hydroxide",
    formula: "KOH",
    type: "base",
    state: "solid",
    cation: "K+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "35",
    name: "Calcium Hydroxide",
    formula: "Ca(OH)2",
    type: "base",
    state: "solid",
    cation: "Ca2+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "36",
    name: "Ammonia Solution",
    formula: "NH3(aq)",
    type: "base",
    state: "aqueous",
    cation: "NH4+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "63",
    name: "Potassium Hydroxide",
    formula: "KOH",
    type: "base",
    state: "solid",
    cation: "K+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "64",
    name: "Calcium Hydroxide",
    formula: "Ca(OH)2",
    type: "base",
    state: "solid",
    cation: "Ca2+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "65",
    name: "Magnesium Hydroxide",
    formula: "Mg(OH)2",
    type: "base",
    state: "solid",
    cation: "Mg2+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "66",
    name: "Barium Hydroxide",
    formula: "Ba(OH)2",
    type: "base",
    state: "solid",
    cation: "Ba2+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "67",
    name: "Lithium Hydroxide",
    formula: "LiOH",
    type: "base",
    state: "solid",
    cation: "Li+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "105",
    name: "Ammonium Hydroxide",
    formula: "NH4OH",
    type: "base",
    state: "aqueous",
    cation: "NH4+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "142",
    name: "Iron(II) Hydroxide",
    formula: "Fe(OH)2",
    type: "base",
    state: "solid",
    cation: "Fe2+",
    anion: "OH-",
    color: "#00FF00",
  },
  {
    id: "143",
    name: "Iron(III) Hydroxide",
    formula: "Fe(OH)3",
    type: "base",
    state: "solid",
    cation: "Fe3+",
    anion: "OH-",
    color: "#FFA500",
  },
  {
    id: "144",
    name: "Nickel(II) Hydroxide",
    formula: "Ni(OH)2",
    type: "base",
    state: "solid",
    cation: "Ni2+",
    anion: "OH-",
    color: "#00FFFF",
  },
  {
    id: "145",
    name: "Cobalt(II) Hydroxide",
    formula: "Co(OH)2",
    type: "base",
    state: "solid",
    cation: "Co2+",
    anion: "OH-",
    color: "#FF00FF",
  },
  {
    id: "146",
    name: "Zinc Hydroxide",
    formula: "Zn(OH)2",
    type: "base",
    state: "solid",
    cation: "Zn2+",
    anion: "OH-",
    color: "#FFFFFF",
  },
  {
    id: "147",
    name: "Aluminum Hydroxide",
    formula: "Al(OH)3",
    type: "base",
    state: "solid",
    cation: "Al3+",
    anion: "OH-",
    color: "#FFFFFF",
  },

  // Oxides
  {
    id: "37",
    name: "Copper Oxide",
    formula: "CuO",
    type: "oxide",
    state: "solid",
    color: "#000000",
  },
  {
    id: "38",
    name: "Iron Oxide",
    formula: "Fe2O3",
    type: "oxide",
    state: "solid",
    color: "#8B0000",
  },
  {
    id: "39",
    name: "Magnesium Oxide",
    formula: "MgO",
    type: "oxide",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "40",
    name: "Calcium Oxide",
    formula: "CaO",
    type: "oxide",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "109",
    name: "Zinc Oxide",
    formula: "ZnO",
    type: "oxide",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "110",
    name: "Aluminum Oxide",
    formula: "Al2O3",
    type: "oxide",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "111",
    name: "Iron(II) Oxide",
    formula: "FeO",
    type: "oxide",
    state: "solid",
    color: "#000000",
  },
  {
    id: "112",
    name: "Iron(III) Oxide",
    formula: "Fe2O3",
    type: "oxide",
    state: "solid",
    color: "#8B0000",
  },
  {
    id: "113",
    name: "Copper(I) Oxide",
    formula: "Cu2O",
    type: "oxide",
    state: "solid",
    color: "#FF0000",
  },
  {
    id: "114",
    name: "Copper(II) Oxide",
    formula: "CuO",
    type: "oxide",
    state: "solid",
    color: "#000000",
  },
  {
    id: "115",
    name: "Lead(II) Oxide",
    formula: "PbO",
    type: "oxide",
    state: "solid",
    color: "#FFFF00",
  },
  {
    id: "116",
    name: "Mercury(II) Oxide",
    formula: "HgO",
    type: "oxide",
    state: "solid",
    color: "#FF0000",
  },
  {
    id: "135",
    name: "Titanium(IV) Oxide",
    formula: "TiO2",
    type: "oxide",
    state: "solid",
    color: "#FFFFFF",
  },
  {
    id: "136",
    name: "Vanadium(V) Oxide",
    formula: "V2O5",
    type: "oxide",
    state: "solid",
    color: "#FFA500",
  },
];
